scrape_configs:
- job_name: 'UserServiceMetrics'
  metrics_path: '/actuator/prometheus'
  scrape_interval: 3s
  static_configs:
    - targets: ['host.docker.internal:8002']
      labels:
        application: 'User Service'