server:
  port: 8001

spring:
  config:
    import: configserver:http://localhost:9296
  application:
    name: DEPARTMENT-SERVICE

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus