spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Mittal-Shivam/sb-ms-config-server
          clone-on-start: true

server:
  port: 9296
